name: .NET 8 Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet build --configuration Release Microsoft.Teams.AI.csproj
      working-directory: dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI
